Repository fourkitchens/emulsify, pull requests merged in 2018-05, with the labels that each got.

#218 Get rid of drush and use a plain PHP script for scaffolding
  emulsify.php
Labels: Status: Passes functional review

#206 SVG sprite method change
  components/_patterns/01-atoms/04-images/00-image/image~logo.yml
  components/_patterns/01-atoms/04-images/icons/_icon.twig
  components/_patterns/01-atoms/04-images/icons/_icon_sprite.scss
  components/_patterns/01-atoms/04-images/icons/_icons.scss
  components/_patterns/01-atoms/04-images/icons/icons.md
  components/_patterns/01-atoms/04-images/icons/icons.twig
  components/_patterns/01-atoms/04-images/icons/icons.yml
  components/_patterns/02-molecules/menus/main-menu/_03-main-menu-toggle.scss
  components/_patterns/02-molecules/menus/main-menu/main-menu.twig
  components/_patterns/05-pages/_styleguide-specific.scss
  components/js/svgxuse.min.js
  emulsify.libraries.yml
  images/icons/src/bars.svg
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit, Type: Enhancement

#229 Added attach_library Twig function in PL
  components/_patterns/01-atoms/04-images/icons/_icon.twig
  components/_patterns/01-atoms/04-images/icons/icons.md
  components/_twig-components/functions/pl_attach-library.function.php
Labels: Priority: Critical, Status: Passes code review, Status: Passes functional review, Status: Shipit

#230 223: Clarify image directory usage
  components/images/README.md
  images/README.md
Labels: Priority: Low, Status: Review Needed

#231 Clearer installation instructions
  README.md
Labels: Priority: Low, Status: Passes code review

#241 Removed duplicate line from .gitignore.
  .gitignore
Labels: Status: Passes code review

#242 Fix help command output
  emulsify.php
Labels: Status: Passes code review, Status: Passes functional review

#239 PL Trans tag: Fixes for 214
  components/_twig-components/tags/pl_trans.tag.php
Labels: Priority: Critical, Status: Passes code review, Status: Passes functional review, Status: Shipit
