Repository fourkitchens/emulsify, pull requests merged in 2018-12, with the labels that each got.

#308 Typo in error message
  emulsify.php
Labels: Priority: Low, Status: Passes code review, Status: Shipit, Type: Documentation

#288 move drupal js loading to head, reload scripts
  components/_meta/_00-head.twig
  components/_meta/_01-foot.twig
  components/js/reload-scripts.js
Labels: Priority: Critical, Status: Review Needed

#309 lock file updates
  package-lock.json
  yarn.lock
Labels: Priority: Critical, Status: Passes code review, Status: Passes functional review, Status: Shipit

#312 222: removed inheritance of ALL item modifiers
  components/_patterns/02-molecules/menus/_menu-item.twig
Labels: Priority: Medium, Status: Passes code review

#314 Minor 3.x fixes
  .stylelintrc
  components/_patterns/00-base/global/base/_pl-base.scss
  package-lock.json
  yarn.lock
Labels: Priority: Low, Status: Review Needed

#311 Removing manual install of composer to check if we even need it anymore.
  .circleci/config.yml
Labels: Status: Passes code review, Status: Passes functional review

#313 291: move icon inside navigation
  components/_patterns/02-molecules/menus/main-menu/_00-main-menu.scss
  components/_patterns/02-molecules/menus/main-menu/main-menu.twig
Labels: Priority: Low, Status: Review Needed
