Repository fourkitchens/emulsify, pull requests merged in 2018-08, with the labels that each got.

#272 CircleCI Setup
  .circleci/config.yml
  README.md
Labels: Status: Review Needed

#280 Remove unused clean task
  package.json
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#245 65: Attach Library used in Pattern Lab
  .gitignore
  components/_meta/_01-foot.twig
  components/_patterns/02-molecules/accordion-item/accordion-item.twig
  components/_patterns/02-molecules/menus/main-menu/main-menu.twig
  components/_patterns/02-molecules/menus/tabs/tabs.twig
  components/_patterns/03-organisms/accordion/accordion.twig
  components/_twig-components/functions/pl_attach-library.function.php
  composer.json
  composer.lock
  emulsify.libraries.yml
  scripts/twig_functions.sh
  templates/navigation/menu--main.html.twig
Labels: Priority: Low, Status: Feedback Needed, Status: Passes code review, Status: Passes functional review

#284 Emulsify gulp major version bump
  package.json
  yarn.lock
Labels: Status: Review Needed
