Repository fourkitchens/emulsify, pull requests merged in 2018-06, with the labels that each got.

#243 Remove old PL CSS ref
  components/_meta/_00-head.twig
Labels: Priority: Low, Status: Passes code review

#246 237: removed JS class on non-JS implementation
  components/_patterns/01-atoms/09-menu/tab/_tab.scss
  components/_patterns/01-atoms/09-menu/tab/tab.twig
Labels: Priority: Low, Status: Review Needed

#253 Improved icon components.
  components/_data/paths.json
  components/_patterns/01-atoms/04-images/icons/_icon.twig
  components/_patterns/01-atoms/04-images/icons/icons.twig
  components/_twig-components/functions/pl_attach-library.function.php
Labels: Status: Passes code review, Status: Passes functional review

#247 244: Remove Singularity
  components/_patterns/00-base/global/base/_02-breakpoints.scss
  components/_patterns/00-base/layouts/_default.scss
  components/_patterns/05-pages/article/article.twig
  components/_patterns/style.scss
Labels: Priority: Low, Status: Passes code review, Status: Passes functional review

#238 177: view example using default frontpage view
  components/_patterns/02-molecules/card/01-card.twig
  components/_patterns/03-organisms/card-grid/card-grid.twig
  templates/content/node--article--teaser.html.twig
  templates/views/views-view-unformatted--frontpage.html.twig
Labels: Status: Passes code review, Status: Passes functional review, Type: Feature
