Repository fourkitchens/emulsify, pull requests merged in 2019-05, with the labels that each got.

#321 315: better accessibility for SVG icons
  components/_patterns/01-atoms/04-images/icons/_icon.twig
  components/_patterns/01-atoms/04-images/icons/icons.md
  components/_patterns/01-atoms/04-images/icons/icons.yml
  components/_patterns/02-molecules/menus/main-menu/main-menu.twig
Labels: Priority: Medium, Status: Review Needed

#333 Add issue/pr templates and welcome bot config.
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/config.yml
Labels: Priority: Medium, Status: Passes code review, Status: Passes functional review, Status: Shipit, Type: Enhancement

#325 Fixes and accessibility testing adding
  README.md
Labels: Priority: Low, Status: Passes code review, Status: Passes functional review

#320 318: minor typo fix
  components/_patterns/01-atoms/02-text/text/03-inline-elements.twig
Labels: Priority: Low, Status: Passes code review, Status: Passes functional review, Status: Shipit
